import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('api', {
  storeGet: (key: string) => ipcRenderer.invoke('store:get', key),
  storeSet: (key: string, val: any) => ipcRenderer.invoke('store:set', key, val),
  storeGetAll: () => ipcRenderer.invoke('store:getAll'),
  tabsCreate: (url: string) => ipcRenderer.invoke('tabs:create', url),
  tabsClose: (id: string) => ipcRenderer.invoke('tabs:close', id),
  tabsReorder: (order: string[]) => ipcRenderer.invoke('tabs:reorder', order),
  tabsTogglePinned: (id: string) => ipcRenderer.invoke('tabs:togglePinned', id),
  tabsToggleMuted: (id: string) => ipcRenderer.invoke('tabs:toggleMuted', id),
  siteSetBaseUrl: (url: string) => ipcRenderer.invoke('site:setBaseUrl', url),
  tabsSwitch: (id: string) => ipcRenderer.invoke('tabs:switch', id),
  tabsNavigate: (id: string, url: string) => ipcRenderer.invoke('tabs:navigate', id, url),
  viewSet: (mode: string) => ipcRenderer.invoke('view:set', mode),
  sidebarSetCollapsed: (v: boolean) => ipcRenderer.invoke('sidebar:setCollapsed', v),
  appVersion: () => ipcRenderer.invoke('app:version'),
  appCheckUpdate: () => ipcRenderer.invoke('app:checkUpdate'),
  appOpenUrl: (url: string) => ipcRenderer.invoke('app:openUrl', url),
  appNotify: (text: string) => ipcRenderer.invoke('app:notify', text),
  onAppNotice: (cb: (text: string) => void) => ipcRenderer.on('app:notice', (_e, text) => cb(String(text || ''))),
  accountsList: () => ipcRenderer.invoke('accounts:list'),
  accountsAdd: () => ipcRenderer.invoke('accounts:add'),
  accountsSelect: (id: string) => ipcRenderer.invoke('accounts:select', id),
  accountsSetNickname: (id: string, nickname: string) => ipcRenderer.invoke('accounts:setNickname', id, nickname),
  accountsRemove: (id: string) => ipcRenderer.invoke('accounts:remove', id),
  achievementsFetch: () => ipcRenderer.invoke('achievements:fetch'),
  detectorToggle: () => ipcRenderer.invoke('detector:toggle'),
  detectorSound: () => ipcRenderer.invoke('detector:sound'),
  detectorToast: () => ipcRenderer.invoke('detector:toast'),
  followbackToggle: () => ipcRenderer.invoke('followback:toggle'),
  onDetectorUpdated: (cb: (d: any) => void) => ipcRenderer.on('detector:updated', (_e, d) => cb(d)),
  onAnomalyDetected: (cb: (info: any) => void) => ipcRenderer.on('anomaly:detected', (_e, info) => cb(info || {})),
  googleLogin: () => ipcRenderer.invoke('google:login'),
  onTabsUpdated: (cb: (tabs: any, activeTabId: string | null) => void) => ipcRenderer.on('tabs:updated', (_e, tabs, activeTabId) => cb(tabs, activeTabId)),
  onAccountsUpdated: (cb: (accounts: any[], activeId: string) => void) => ipcRenderer.on('accounts:updated', (_e, accounts, activeId) => cb(accounts, activeId)),
  onTabsLimit: (cb: () => void) => ipcRenderer.on('tabs:limit', () => cb()),
  onFollowbackDone: (cb: (names: string[]) => void) => ipcRenderer.on('followback:done', (_e, names) => cb(Array.isArray(names) ? names : [])),
  onFollowbackTick: (cb: (ts: number, summary: any) => void) => ipcRenderer.on('followback:tick', (_e, ts, summary) => cb(Number(ts) || 0, summary || null)),
  followbackReset: () => ipcRenderer.invoke('followback:reset'),
  winMinimize: () => ipcRenderer.send('win:minimize'),
  winMaximize: () => ipcRenderer.send('win:maximize'),
  winClose: () => ipcRenderer.send('win:close')
})
