import { useEffect, useMemo, useState } from 'react'

const SECRETS = [
  ['secret_iddqd', 'IDDQD', 'Раздел «Аниме»: ввести IDDQD в поиск, Enter'], ['secret_konami', 'Код на память', 'На главной с компьютера: ↑↑↓↓←→←→BA, английская раскладка'], ['secret_deep_night', 'Три часа ночи', '7 раз зайти около 03:00 МСК, когда на сайте никого нет'], ['secret_rewatch', 'Дежавю', 'Полностью посмотреть один тайтл трижды'], ['secret_leet_minute', '13:37', 'Смотреть аниме в 13:37 по Москве'], ['secret_not_found', 'Не туда свернул', 'Открыть несуществующую страницу (ошибка 404)'], ['secret_round_xp', 'Ноль в ноль', 'Круглый общий опыт (например, 1000 или 2000 XP)'], ['secret_witness', 'Свидетель патча', 'Быть на сайте в момент установки обновления'], ['secret_midnight_start', 'Полночная премьера', 'Начать просмотр аниме ровно в 00:00 МСК'], ['secret_same_day_release', 'Ровесник', 'Начать смотреть аниме, вышедшее в день твоей регистрации'], ['secret_frame_24', 'Двадцать четвёртый кадр', 'Код из анимации другой секретки — в поиск на главной'], ['secret_exchange', 'Равноценный обмен', 'Потратить ровно столько монеток, сколько заработал после 00:00'], ['secret_binge_finish', 'Тайминг', 'Досмотреть к релизу новой серии'], ['secret_midnight_anomaly', 'Первая минута', 'Поймать аномальную сущность ровно в 00:00 МСК'], ['secret_nine_lives', 'Девять жизней', 'Собрать 9 кодов формата NYA-****-****'], ['secret_2501', '2501', 'Пройти 2 этап в терминале'], ['secret_thousand_minus_seven', '1000-7', 'Вписать в консоль 1000-7'], ['secret_last_second', 'На флажке', 'Завершить последнее задание дня в 23:59 МСК'], ['secret_third_september', 'Третье сентября', 'Я календарь переверну — и снова третье сентября.'], [null, 'Все голоса', 'Минимум по серии в каждой озвучке одного тайтла'], [null, 'Внахлёст', 'Закончить последнюю серию в момент выхода новой']
].map(([code, name, desc], i) => ({ code, key: code || `community_${i}`, name, desc }))
// Удалены из игры + неверные догадки (дубли существующих): quest_deadline = На флажке
const OBSOLETE_SECRET_CODES = new Set(['secret_anniversary', 'secret_registration_date', 'secret_registration', 'secret_quest_deadline'])

const LockIcon = () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3" /></svg>
const SparkIcon = () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 1.5 5.5L19 10l-5.5 1.5L12 17l-1.5-5.5L5 10l5.5-1.5L12 3Z"/><path d="m19 16 .7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7L19 16Z"/></svg>

export default function Secrets() {
  const [ach, setAch] = useState(null); const [catalog, setCatalog] = useState(SECRETS); const [synced, setSynced] = useState(false); const [loading, setLoading] = useState(false); const [err, setErr] = useState(''); const [filter, setFilter] = useState('all')
  const isSecretAchievement = (a) => {
    const code = String(a?.code || a?.key || a?.slug || '').toLowerCase()
    const kind = String(a?.type || a?.category || a?.group || '').toLowerCase()
    return code.startsWith('secret_') || code.startsWith('secret-') || a?.isSecret === true || a?.is_secret === true || kind === 'secret' || kind === 'secrets'
  }
  const normalizeRemote = (items) => items.filter(a => { const code = String(a?.code || a?.key || a?.slug || '').toLowerCase(); const name = String(a?.name || a?.title || '').toLowerCase(); return a?.code && !OBSOLETE_SECRET_CODES.has(code) && !name.includes('дата регистрации') && (code.startsWith('secret_') || code.startsWith('secret-')) && isSecretAchievement(a) }).map(a => ({ code: String(a.code), name: String(a.name || a.title || a.code), desc: String(a.description || a.desc || a.hint || 'Секретка из профиля AnimeOn') }))
  const fetchLive = async () => { setLoading(true); setErr(''); try { const res = await window.api?.achievementsFetch(); if (!res?.ok) setErr(res?.error || 'Нет вкладки или не залогинен'); else { setAch(res.data); const raw = res.data?.data ?? res.data; const items = Array.isArray(raw) ? raw : (raw?.achievements ?? raw?.items ?? raw?.list ?? []); const remote = normalizeRemote(items); setCatalog(prev => { const next = [...prev]; for (const r of remote) { if (next.some(s => s.code === r.code)) continue; const idx = next.findIndex(s => !s.code && String(s.name || '').trim().toLowerCase() === String(r.name || '').trim().toLowerCase() && String(r.name || '').trim().length > 0); if (idx !== -1) next[idx] = { ...next[idx], code: r.code, name: r.name, desc: r.desc || next[idx].desc }; else next.push(r) } window.api?.storeSet?.('secretsCatalog', next); return next }); setSynced(true) } } catch (e) { setErr(String(e)) } setLoading(false) }
  useEffect(() => { window.api?.storeGet?.('secretsCatalog').then(saved => { if (Array.isArray(saved) && saved.length) setCatalog([...SECRETS, ...saved.filter(s => s?.code && !OBSOLETE_SECRET_CODES.has(String(s.code).toLowerCase()) && String(s.name || '').toLowerCase() !== 'дата регистрации' && !SECRETS.some(x => x.code === s.code))]) }); fetchLive() }, [])
  const list = useMemo(() => { const raw = ach; if (!raw) return []; const data = raw.data ?? raw; return Array.isArray(data) ? data : (data.achievements ?? data.items ?? data.list ?? []) }, [ach])
  const byCode = new Map(list.filter(a => a.code).map(a => [a.code, a]))
  const secretCatalog = catalog.filter(s => { const c = String(s.code || ''); if (OBSOLETE_SECRET_CODES.has(c.toLowerCase())) return false; if (String(s.name || '').toLowerCase() === 'дата регистрации') return false; if (!c) return !!s.key; return c.startsWith('secret_') || SECRETS.some(base => base.code === s.code) })
  const displayed = useMemo(() => secretCatalog.map(s => { const a = s.code ? byCode.get(s.code) : undefined; const has = !!a; const done = !!a?.completed; return { ...s, done, opened: synced && has, codeShown: synced && has ? s.code : '······', prog: has ? `${a.progress ?? 0}/${a.threshold ?? 1}` : '—' } }).filter(s => filter === 'all' || (filter === 'done' ? s.done : !s.done)).sort((a, b) => Number(b.done) - Number(a.done)), [catalog, list, synced, filter])
  const doneCount = secretCatalog.filter(s => byCode.get(s.code)?.completed).length
  const completion = secretCatalog.length ? Math.round((doneCount / secretCatalog.length) * 100) : 0

  return <div className="h-full overflow-auto px-6 py-6 text-white"><div className="mx-auto max-w-[920px] space-y-5">
    <header className="grid gap-4 md:grid-cols-[1fr_auto] md:items-end"><div><div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.18em] text-violet-300/80"><SparkIcon /> Коллекция открытий</div><h1 className="mt-2 text-[28px] font-semibold tracking-tight">Секреты</h1><p className="mt-1 text-sm text-zinc-400">Скрытые задания AnimeOn, которые уже удалось найти.</p></div><button onClick={fetchLive} disabled={loading} className="h-10 rounded-xl bg-white px-4 text-sm font-medium text-black transition hover:bg-zinc-200 disabled:opacity-50">{loading ? 'Синхронизация...' : 'Синхронизировать'}</button></header>
    {err && <div className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-xs text-red-300">{err}. Откройте AnimeOn и войдите в аккаунт.</div>}
    <section className="grid gap-4 rounded-2xl border border-white/10 bg-[#141521] p-5 sm:grid-cols-[1fr_170px] sm:items-center"><div><div className="flex items-center gap-2 text-xs text-zinc-400"><LockIcon size={15} /> Прогресс коллекции</div><div className="mt-2 flex items-end gap-3"><span className="text-4xl font-semibold tracking-tight">{doneCount}</span><span className="pb-1 text-sm text-zinc-500">из {secretCatalog.length} секретов</span></div><div role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow={completion} className="mt-4 h-2.5 overflow-hidden rounded-full bg-[#292a38]"><div className="h-full rounded-full bg-violet-400 shadow-[0_0_12px_rgba(167,139,250,.65)] transition-[width] duration-500" style={{ width: `${completion}%` }} /></div></div><div className="text-left sm:text-right"><div className="text-3xl font-semibold text-violet-200">{completion}%</div><div className="mt-1 text-xs text-zinc-500">{synced ? 'синхронизировано' : 'ожидает входа'}</div></div></section>
    <div className="flex flex-wrap items-center gap-2"><span className="mr-2 text-xs text-zinc-500">Показывать:</span>{[['all', 'Все'], ['done', 'Полученные'], ['open', 'Не полученные']].map(([id, label]) => <button key={id} onClick={() => setFilter(id)} className={`rounded-lg border px-3 py-2 text-xs transition ${filter === id ? 'border-violet-400/50 bg-violet-500/15 text-violet-200' : 'border-white/10 bg-white/[0.03] text-zinc-400 hover:text-white'}`}>{label}</button>)}</div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{displayed.map((d, i) => <article key={d.key || d.code} className={`relative overflow-hidden rounded-xl border p-4 transition ${d.done ? 'border-emerald-400/20 bg-emerald-400/[0.06]' : 'border-white/10 bg-[#11121b] hover:border-violet-400/30'}`}><div className="flex items-start justify-between gap-3"><div className={`grid h-9 w-9 place-items-center rounded-lg ${d.done ? 'bg-emerald-400/15 text-emerald-300' : 'bg-white/[0.06] text-zinc-500'}`}>{d.done ? '✓' : <LockIcon size={16} />}</div><span className="font-mono text-[10px] text-zinc-600">#{String(i + 1).padStart(2, '0')}</span></div><h2 className="mt-4 text-sm font-medium text-white">{d.name}</h2><p className="mt-1 min-h-[34px] text-xs leading-relaxed text-zinc-500">{d.desc}</p><div className="mt-4 flex items-center justify-between border-t border-white/[0.06] pt-3"><span className="font-mono text-[10px] text-zinc-500">{d.opened ? d.code : d.codeShown}</span><span className={`text-[11px] ${d.done ? 'text-emerald-300' : 'text-zinc-600'}`}>{d.done ? 'получено' : d.opened ? `прогресс ${d.prog}` : 'не открыто'}</span></div></article>)}</section>
    <div className="text-[11px] text-zinc-600">{synced ? 'Данные получены из текущей сессии AnimeOn.' : 'Синхронизируйте секреты после входа в AnimeOn.'}</div>
  </div></div>
}
